spring:
  application:
      name: simple-service
  profiles:
    active: local
---
spring:
  config:
    activate:
      on-profile: local
  data:
    mongodb:
      host: localhost
      port: 27017
      database: local
---
logging:
  level:
    root: info